### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by lenamariahackl** [YStrauch/CI-SpliceAI__Annotation#1]
Hi, thank you for your work. I am trying to reproduce the CI-SpliceAI model but running "python create_data.py" results in an assertion error after 93% progress at line 87 "assert len(x) == len(y)".

**Comment by YStrauch** [comment]
Hi!

Thank you for reaching out. First of all, you're in the wrong repository as this one is the annotation library, issues regarding training should be posted to https://github.com/YStrauch/CI-SpliceAI__Train please. This is why I'm going to close this issue.

But also I've just tried the create_data.py and it runs through without issue for me. I even made sure to do a clean checkout on a computer that didn't previously run the project, so I am not sure how I could help you - would need to debug the code...
